VideoChatProject/Site/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^upload/', include('uploader.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^play/', include('VideoChat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VideoChatProject/uploader/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from . import views

app_name = 'uploader'

urlpatterns = [
    url(r'^$', views.upload, name='index'),
    url(r'^image$', views.upload_image, name='image'),
]

VideoChatProject/videochat/urls.py
from django.conf.urls import url
from . import views
from . import ajax
app_name = 'videochat'

urlpatterns = [
    # ... the rest of your URLconf goes here ...
    url(r'^ajax/add_friend/$', ajax.add_friend),
    url(r'^ajax/cancel_fr/$', ajax.cancel_fr),
    url(r'^ajax/get_last_event/$', ajax.get_last_event, name='gle'),
    url(r'^ajax/handle_events/$', ajax.handle_events, name='he'),
    url(r'^ajax/handle_request/$', ajax.handle_request),
    url(r'^ajax/finish_watching/$', ajax.finish_watching),
    url(r'^ajax/delete_friend/$', ajax.delete_friend),
    url(r'^ajax/delete_video/$', ajax.delete_video),

    url(r'^u/(?P<user_id>[0-9]+)/$', views.user, name='u'),
    #url(r'^v/(?P<video_id>[0-9]+)(?:/(?P<chatroom_id>[0-9]+))?/$', views.play, name='v'),
    url(r'^v/(?P<video_id>[0-9]+)(?:/(?P<chatroom_id>[0-9]+))?/$', views.play, name='v'),

    url(r'^newchatmessage/$', views.newchatmessage, name='newchatmessage'),
    url(r'^getchatmessages/$', views.getchatmessages, name='getchatmessages'),
    url(r'^fr/(?P<user_id>[0-9]+)/$', views.friendship_requests, name='fr'),
]

VideoChatProject/website/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views
from django.contrib.auth.views import logout
urlpatterns = [
    url(r'^login/', views.login_view, name="login_view"),
    url(r'^logout/', logout , {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^register/', views.register_view, name='register_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^upload/', include('uploader.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^vc/', include('videochat.urls')),
    url(r'^$', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VideoChatProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js"><\/script>')
    </script>
    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VideoChat - {% block title %}{% endblock %}</title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

    <!-- Bootstrap and Font Awesome css -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Css animations  -->
    <link href="{% static "/css/animate.css" %}" rel="stylesheet">

    <!-- Theme stylesheet, if possible do not edit this stylesheet -->
    <link href="{% static "/css/style.red.css" %}" rel="stylesheet" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes -->
    <link href="{% static "/css/custom.css" %}" rel="stylesheet">

    <!-- Responsivity for older IE -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<   ![endif]-->

    <!-- owl carousel css -->

    <link href="{% static "/css/owl.carousel.css" %}" rel="stylesheet">
    <link href="{% static "/css/owl.theme.css" %}" rel="stylesheet">

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    </head>
    <body>

        {% include 'navbar.html' %}

        <div>
             <section class="bar background-gray no-mb">

            {% block body_block %}
            {% endblock %}

             </section>
        </div>
    </body>

    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/css/bootstrap-select.min.css">


    <script src="{% static "/js/jquery.cookie.js" %}"></script>
    <script src="{% static "/js/waypoints.min.js" %}"></script>
    <script src="{% static "/js/jquery.counterup.min.js" %}"></script>
    <script src="{% static "/js/jquery.parallax-1.1.3.js" %}"></script>
    <script src="{% static "/js/front.js" %}"></script>

    <!-- owl carousel -->
    <script src="{% static "/js/owl.carousel.min.js" %}"></script>
    <hr>
    {% include 'footer.html' %}

    {% block scripts_block %}
    {% endblock %}
</html>

VideoChatProject/templates/footer.html
<div id="copyright">
    <div class="container">
        <div class="col-md-12">
            <p class="pull-left">&copy; 2016. VideoChat</p>
            <p class="pull-right">Template adapted from <a href="https://bootstrapious.com/free-templates">Bootstrapious</a>
            </p>
        </div>
    </div>
</div>

VideoChatProject/templates/index.html
{% extends 'base.html' %}
{% block title %} Watch videos with your friends {% endblock %}
{% load static %}
{% load videochat_extras %}

{% block body_block %}
    <div id="heading-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="heading text-center">
                    <h2>From your friends</h2>
                </div>
                <p class="lead text-center">Enjoy the videos that your friends are watching now</p>
            </div>
        </div>
    </div>
    <div class="container">
        {% with results=videos_being_watched|get_tuples:4 %}
            {% for tuple in results %}
                <div class="col-md-12">
                    <div class="row">
                        {% for friend, result, chatroom in tuple %}
                            <div class="col-md-3 col-sm-6">
                                <div class="box-image-text blog">
                                    <div class="top">
                                        <div class="image">
                                            <img src="{% static "/img/portfolio-4.jpg" %}" alt="" class="img-responsive">
                                        </div>

                                        <div class="bg"></div>

                                        <div class="text">
                                            <p class="buttons">
                                                <a href="{% url 'videochat:v' result.pk chatroom.pk %}" class="btn btn-template-transparent-primary"><i class="fa fa-play"></i> Play</a>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="content">
                                        <h4><a href="#">{{ result.title }}</a></h4>

                                        <p class="author-category">Being watched by <a href="{% url 'videochat:u' friend.pk %}">{{ friend.username }}</a>
                                        <p class="author-category">Uploaded by <a href="{% url 'videochat:u' result.author.pk %}">{{ result.author.username }}</a>

                                        </p>

                                        <p class="intro">{{ result.description }}</p>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% empty %}
                <p>Nobody is watching videos by the moment.</p>
            {% endfor %}
        {% endwith %}
    </div>
{% endblock %}

VideoChatProject/templates/login.html
{% extends 'outside_base.html' %}
{% block title %}
   Share your videos with the world
{% endblock %}
{% block body_block %}
    <div class="container">
        <div class="home-carousel">
                            <div class="dark-mask"></div>

            <div class="container">
                <div class="homepage owl-carousel">
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-5 right">
                                <h1>Enjoy videos with friends</h1>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-5">
                                <h2>Chat with <br> people who are watching the same video</h2>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="row">
                            <div class="col-sm-5 right">
                                <h1>Meet great people, make friends</h1>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.project owl-slider -->
            </div>
        </div>
    </div>

<!-- Upload form. Note enctype attribute! -->

{% endblock %}

VideoChatProject/templates/navbar.html
<div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">
    <div class="navbar navbar-default yamm" role="navigation" id="navbar">
        {% load static %}

        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand home" href="{% url 'index' %}">
                    <img src="{% static "/img/logo.png" %}" alt="VideoChat logo" class="hidden-xs hidden-sm"/>
                    <img src="{% static "/img/logo-small.png" %}" alt="VideoChat logo" class="visible-xs visible-sm">
                    <span class="sr-only">VideoChat - Go to homepage</span>

                </a>


                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-align-justify"></i>
                    </button>
                </div>
                <div id="search-outer-sm"  class="visible-sm">
                    <form id="search-form" role="search" method="get" action="/search/">
                        <select class="search-select" name="models">
                          <option value="videochat.video">Video</option>
                          <option value="auth.user">User</option>
                        </select>
                        <input id="search-input" type="text" class="form-control search-input" placeholder="Search" name="q">
                        <button id="search-submit" type="submit" class="search-button btn btn-template-main btn-search"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <div id="search-outer"  class="hidden-xs hidden-sm">
                    <form id="search-form" role="search" method="get" action="/search/">
                       <select class="search-select" name="models">
                          <option value="videochat.video">Video</option>
                          <option value="auth.user">User</option>
                        </select>
                        <input id="search-input" type="text" class="form-control search-input" placeholder="Search" name="q">
                        <button id="search-submit"  type="submit" class="search-button btn btn-template-main btn-search"><i class="fa fa-search"></i></button>
                    </form>
                </div>
               <div id="search-outer-xs"  class="visible-xs">
                    <form id="search-form" role="search" method="get" action="/search/">
                       <select class="search-select" name="models">
                          <option value="videochat.video">Video</option>
                          <option value="auth.user">User</option>
                        </select>
                        <input id="search-input" type="text" class="form-control search-input" placeholder="Search" name="q">
                        <button id="search-submit"  type="submit" class="search-button btn btn-template-main btn-search"><i class="fa fa-search"></i></button>
                    </form>
               </div>

            </div>

            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a style="text-decoration: none;" href="{% url 'uploader:index' %}">Upload <b></b></a>
                    </li>
                     <li class="dropdown">
                            <a style="margin-bottom: -15px"; class="img-a dropdown-toggle" data-toggle="dropdown" href="javascript: void(0)"><img src="{{ request.user.profile.image.url }}" alt="" class="img-small"></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'videochat:u' request.user.pk %}">My profile: {{ request.user.username }}</a>
                                </li>
                                <li><a href="{% url 'videochat:fr' request.user.pk %}">Friend requests</a>
                                </li>
                                <li><a href="{% url 'uploader:image' %}">Change image</a>
                                </li>
                                <li><a href="/logout/">Sign out</a>
                                </li>

                            </ul>
                     </li>
                </ul>

            </div>

            <div class="collapse clearfix" id="search">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </form>

            </div>

        </div>


    </div>

</div>

VideoChatProject/templates/outside_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VideoChat - {% block title %}{% endblock %}</title>

    <meta name="keywords" content="">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

    <!-- Bootstrap and Font Awesome css -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Css animations  -->
    <link href="{% static "/css/animate.css" %}" rel="stylesheet">

    <!-- Theme stylesheet, if possible do not edit this stylesheet -->
    <link href="{% static "/css/style.red.css" %}" rel="stylesheet" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes -->
    <link href="{% static "/css/custom.css" %}" rel="stylesheet">

    <!-- Responsivity for older IE -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<   ![endif]-->

    <!-- owl carousel css -->

    <link href="{% static "/css/owl.carousel.css" %}" rel="stylesheet">
    <link href="{% static "/css/owl.theme.css" %}" rel="stylesheet">
    </head>
    <body>
        <div>
             <section class="bar background-gray no-mb">
            {% include 'outside_topbar.html' %}
            {% block body_block %}
            {% endblock %}

             </section>
        </div>
    </body>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js"><\/script>')
    </script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/css/bootstrap-select.min.css">


    <script src="{% static "/js/jquery.cookie.js" %}"></script>
    <script src="{% static "/js/waypoints.min.js" %}"></script>
    <script src="{% static "/js/jquery.counterup.min.js" %}"></script>
    <script src="{% static "/js/jquery.parallax-1.1.3.js" %}"></script>
    <script src="{% static "/js/front.js" %}"></script>

    <!-- owl carousel -->
    <script src="{% static "/js/owl.carousel.min.js" %}"></script>
    <hr>
    {% include 'footer.html' %}
</html>

VideoChatProject/templates/outside_topbar.html
<div id="top">
            <div class="container">
                <div class="row">
                    <div class="col-xs-5 contact">
                        <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>  <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
                        </p>
                    </div>
                    <div class="col-xs-7">
                        <div class="login">
                            <a href="/register"><i class="fa fa-user"></i> <span class="hidden-xs text-uppercase">Sign up</span></a>
                            <a href="#" data-toggle="modal" data-target="#login-modal"><i class="fa fa-sign-in"></i> <span class="hidden-xs text-uppercase">Sign in</span></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
    <div class="modal-dialog modal-sm">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="Login">Login</h4>
            </div>
            <div class="modal-body">
                                    {% if next %}
                    <form action="{% url 'login_view' %}?next={{ next }}" method="post" enctype="multipart/form-data">
                {% else %}
                    <form action="{% url 'login_view' %}" method="post" enctype="multipart/form-data">
                {% endif %}
                {% csrf_token %}
                {% for field in form %}
                    <h4>{{ field.label_tag }}</h4>
                    <h4>{{ field }}</h4>
                {% endfor %}

                {% if errors %}
                    <ul>
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                    </ul>
                {% endif %}
                    <button type="submit" class="btn btn-template-main"><i class="fa fa-sign-in"></i> Log in</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% load static %}
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="heading text-center">
                <h1><a href="/"><img src="{% static "img/logo.png" %}" alt="" class="img-responsive"></a></h1>
            </div>
            <p class="lead text-center">Share your videos with the world</p>
        </div>
    </div>
</div>

VideoChatProject/templates/register.html
{% extends 'outside_base.html' %}
{% block title %}
 Sign up
{% endblock %}
{% block body_block %}
    <div class="container">
        <form action="{% url 'register_view' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                
                    <h4>{{ field.label_tag }}</h4>
                    <h4>{{ field }}</h4>
                    {% if field.errors %}
                      <ul>
                        {% for error in field.errors %}
                          <li>{{ error }}</li>
                        {% endfor %}
                      </ul>
                    {% endif %}
                {% endfor %}

            <button type="submit" class="btn btn-template-main"><i class="fa fa-user"></i> Sign up</button>
        </form>
    </div>

<!-- Upload form. Note enctype attribute! -->

{% endblock %}