VideoChatProject/Site/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^upload/', include('uploader.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^play/', include('VideoChat.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VideoChatProject/uploader/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from . import views

app_name = 'uploader'

urlpatterns = [
    url(r'^$', views.upload, name='index'),
    url(r'^image$', views.upload_image, name='image'),
]

VideoChatProject/website/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views
from django.contrib.auth.views import logout
urlpatterns = [
    url(r'^login/', views.login_view, name="login_view"),
    url(r'^logout/', logout , {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^register/', views.register_view, name='register_view'),
    url(r'^admin/', admin.site.urls),
    url(r'^upload/', include('uploader.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^vc/', include('videochat.urls')),
    url(r'^$', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VideoChatProject/uploader/forms.py
from django import forms
from .validators import validate_file_extension

class UploadFileForm(forms.Form):
  title = forms.CharField(label="Title", max_length=50)
  description = forms.CharField(label="Description", widget=forms.Textarea)
  video_file = forms.FileField(
      label='Select a video',
      help_text='max. 20 megabytes',
      validators=[validate_file_extension]
  )

VideoChatProject/uploader/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from haystack.management.commands import update_index
from website.settings import MEDIA_ROOT
from uploader.forms import UploadFileForm
from videochat.models import Video
from django import forms
import os


class ImageUploadForm(forms.Form):
    image = forms.ImageField()


@login_required
def upload_image(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            request.user.profile.image = request.FILES['image']
            request.user.profile.save()

            return render(request, 'upload_image.html', {'alert': 'success'})

        return render(request, 'upload_image.html', {'form': form})
    else:
        form = ImageUploadForm()
        return render(request, 'upload_image.html', {'form': form})


@login_required
def upload(request):
    if request.method == 'POST':
        user = request.user
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            upload_model = Video(
                title=form.cleaned_data['title'],
                description=form.cleaned_data['description'],
                path=request.FILES['video_file'],
                author=user,
                )

            upload_model.save()

            video_path = str(upload_model.path).replace("/", "").replace(".", "")

            filename = "{}thumb_{}.png".format("media/images/thumbnails/", video_path)
            command = "ffmpeg -i media/{} -vf  \"thumbnail,scale=1000:750\" -frames:v 1 {}".format(upload_model.path, filename)
            os.system(command)

            upload_model.thumbnail = "/" + filename
            upload_model.save()

            update_index.Command().handle()

            return render(request, 'upload.html', {'alert': 'success'})
        return render(request, 'upload.html', {'form': form})
    else:
        form = UploadFileForm()
        return render(request, 'upload.html', {'form': form})

VideoChatProject/uploader/templates/upload.html
{% extends 'base.html' %}
{% block title %}
Upload your video!
{% endblock %}
{% block body_block %}
    <div id="heading-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="heading text-center">
                    <h2>Upload videos</h2>
                </div>
                <p class="lead text-center">Share your videos with the world</p>
            </div>
        </div>
    </div>
    <div class="container">
        {% if alert %}
            {% ifequal alert 'success' %}
                <div class="alert alert-success" role="alert">Well done! You successfully uploaded a video.</div>
            {% endifequal %}
        {% else %}
            <form action="{% url 'uploader:index' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {% for field in form %}
                    <h4>{{ field.label_tag }}</h4>
                    <h4>{{ field }}</h4>
                    {% if field.errors %}
                      <ul>
                        {% for error in field.errors %}
                          <li>{{ error }}</li>
                        {% endfor %}
                      </ul>
                    {% endif %}

                {% endfor %}
                    <hr>
            <input class="btn btn-lg btn-template-main" type="submit" value="Upload" />
        </form>
        {% endif %}
    <hr>
    </div>

<!-- Upload form. Note enctype attribute! -->

{% endblock %}

VideoChatProject/uploader/templates/upload_image.html
{% extends 'base.html' %}
{% block title %}
Upload your profile image
{% endblock %}
{% block body_block %}
    <div id="heading-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="heading text-center">
                    <h2>Upload a profile image</h2>
                </div>
                <p class="lead text-center">Let your friends know more about you</p>
            </div>
        </div>
    </div>
    <div class="container">
        {% if alert %}
            {% ifequal alert 'success' %}
                <div class="alert alert-success" role="alert">Well done! You successfully uploaded an image.</div>
            {% endifequal %}
        {% else %}

        <form action="{% url 'uploader:image' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>
                <input id="id_image" type="file" class="" name="image">
            </p>
            <hr></hr>

            <input class="btn btn-lg btn-template-main" type="submit" value="Upload" />

        </form>
        {% endif %}
    <hr>
    </div>

<!-- Upload form. Note enctype attribute! -->

{% endblock %}